In [16]:
import pandas as pd
import numpy as np
import seaborn as sns
import pyreadstat as pyr
import statsmodels.formula.api as smf

In [2]:
# 导入数据，描述性统计，清洗
df, meta = pyr.read_dta(r"C:\Users\Friday\OneDrive\Desktop\statistics\计量经济学\因果推断(数据集）\第三讲演示数据和do文件\DD_wide.dta")
null_list = {}
for column in df.columns:
    null_num = df[column].isnull().sum()
    null_list[column] = null_num
print(null_list)
df.describe()

{'id': np.int64(0), 'fisrev2': np.int64(0), 'exp2': np.int64(0), 'fisrev1': np.int64(0), 'exp1': np.int64(0), 'treat': np.int64(0)}

,id,fisrev2,exp2,fisrev1,exp1,treat
count,1062.000000,1062.000000,1062.000000,1062.000000,1062.000000,1062.000000
mean,663.525424,11615.159066,1783.289018,9708.927236,1226.910088,0.191149
std,438.775254,9750.416642,730.791971,9110.900399,632.826619,0.393391
min,2.000000,541.804993,639.612976,502.696014,345.682007,0.000000
25%,296.250000,4164.682495,1261.281769,3296.666992,834.910522,0.000000
50%,591.500000,8909.780762,1604.451477,6907.113525,1086.765503,0.000000
75%,988.750000,15843.175293,2139.964722,12694.218750,1452.867462,0.000000
max,1529.000000,49841.914062,5527.094238,49451.789062,8084.583008,1.000000

In [3]:
df.head(10)

   id       fisrev2         exp2       fisrev1         exp1  treat
0   2  15177.071289  3013.943115   8158.963867   970.947021    0.0
1   3  23095.658203  3192.278076  17955.931641  2117.831055    0.0
2   4  13042.378906  2263.341064   7595.400879  1308.708008    0.0
3   5  25833.671875  1391.187012  17859.964844  1052.800049    0.0
4   6  26527.490234  1509.189941  19080.234375  1045.272949    0.0
5   8  15304.833008  1788.668945   8920.103516  1224.032959    0.0
6   9   5753.729980  1906.671997   4144.399902  1302.123047    0.0
7  10   7247.836914  1990.072021   3520.623047  1558.972046    0.0
8  12   4082.176025  2360.050049   3171.572021  2183.689941    0.0
9  13  20611.396484  1612.995972   9963.495117  1210.860962    0.0

In [18]:
treat_counts = df["treat"].value_counts()
print(treat_counts)

treat
0.0    859
1.0    203
Name: count, dtype: int64

In [6]:
# 原数据集为宽面版，转化为长面板
df_long = pd.wide_to_long(
    df,
    stubnames=["fisrev","exp"],
    i=["id","treat"],
    j="year"    
).reset_index()

df_long.head()

   id  treat  year        fisrev          exp
0   2    0.0     2  15177.071289  3013.943115
1   2    0.0     1   8158.963867   970.947021
2   3    0.0     2  23095.658203  3192.278076
3   3    0.0     1  17955.931641  2117.831055
4   4    0.0     2  13042.378906  2263.341064

In [29]:
df_long.describe()
df_long["treat"] = df_long["treat"].astype("float").astype("int")

In [30]:
# 不控制人均财政收入和控制人均财政收入前提下回归
model_1 = smf.ols("exp~treat+year",data=df_long)
result_1 = model_1.fit()
print(result_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    exp   R-squared:                       0.186
Model:                            OLS   Adj. R-squared:                  0.185
Method:                 Least Squares   F-statistic:                     241.6
Date:                Sun, 14 Jun 2026   Prob (F-statistic):           2.93e-95
Time:                        16:10:27   Log-Likelihood:                -16822.
No. Observations:                2124   AIC:                         3.365e+04
Df Residuals:                    2121   BIC:                         3.367e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    595.8608     46.250     12.883      0.000     505.160     686.562
treat        390.6399     36.764     10.626      0.000     318.542     462.737
year         556.3789     28.912     19.244      0.000     499.681     613.077
==============================================================================
Omnibus:                      963.701   Durbin-Watson:                   0.965
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8288.588
Skew:                           1.931   Prob(JB):                         0.00
Kurtosis:                      11.873   Cond. No.                         6.97
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [31]:
model_2 = smf.ols("exp~treat+year+fisrev",data=df_long)
result_2 = model_2.fit()
print(result_2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    exp   R-squared:                       0.193
Model:                            OLS   Adj. R-squared:                  0.192
Method:                 Least Squares   F-statistic:                     168.7
Date:                Sun, 14 Jun 2026   Prob (F-statistic):           4.38e-98
Time:                        16:10:34   Log-Likelihood:                -16812.
No. Observations:                2124   AIC:                         3.363e+04
Df Residuals:                    2120   BIC:                         3.366e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    648.2313     47.609     13.616      0.000     554.867     741.596
treat        387.3501     36.618     10.578      0.000     315.539     459.161
year         569.0196     28.937     19.664      0.000     512.271     625.768
fisrev        -0.0066      0.002     -4.344      0.000      -0.010      -0.004
==============================================================================
Omnibus:                      945.873   Durbin-Watson:                   0.981
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7915.339
Skew:                           1.896   Prob(JB):                         0.00
Kurtosis:                      11.663   Cond. No.                     5.42e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.42e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
''' 线性回归估计模式下的DID '''
# 1、不控制fisrev的双重差分
df_long["year_treat"] = df_long["year"]*df_long["treat"]
did_1 = smf.ols("exp~treat+year+year_treat",data=df_long)
did_1 = did_1.fit()
print(did_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    exp   R-squared:                       0.187
Model:                            OLS   Adj. R-squared:                  0.186
Method:                 Least Squares   F-statistic:                     162.7
Date:                Sun, 14 Jun 2026   Prob (F-statistic):           6.74e-95
Time:                        16:10:41   Log-Likelihood:                -16820.
No. Observations:                2124   AIC:                         3.365e+04
Df Residuals:                    2120   BIC:                         3.367e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    638.4225     50.792     12.569      0.000     538.815     738.030
treat        167.9772    116.174      1.446      0.148     -59.850     395.804
year         528.0045     32.124     16.437      0.000     465.007     591.002
year_treat   148.4418     73.475      2.020      0.043       4.351     292.532
==============================================================================
Omnibus:                      964.715   Durbin-Watson:                   0.959
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8326.777
Skew:                           1.933   Prob(JB):                         0.00
Kurtosis:                      11.897   Cond. No.                         18.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [33]:
# 2、只控制fisrev
did_2 = smf.ols("exp~treat+year+year_treat+fisrev",data=df_long)
did_2 = did_2.fit()
print(did_2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    exp   R-squared:                       0.194
Model:                            OLS   Adj. R-squared:                  0.193
Method:                 Least Squares   F-statistic:                     127.6
Date:                Sun, 14 Jun 2026   Prob (F-statistic):           9.74e-98
Time:                        16:10:59   Log-Likelihood:                -16811.
No. Observations:                2124   AIC:                         3.363e+04
Df Residuals:                    2119   BIC:                         3.366e+04
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    688.1344     51.888     13.262      0.000     586.378     789.891
treat        175.7829    115.712      1.519      0.129     -51.138     402.704
year         541.9234     32.155     16.853      0.000     478.864     604.983
year_treat   141.0676     73.194      1.927      0.054      -2.471     284.607
fisrev        -0.0066      0.002     -4.300      0.000      -0.010      -0.004
==============================================================================
Omnibus:                      947.069   Durbin-Watson:                   0.976
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7954.957
Skew:                           1.898   Prob(JB):                         0.00
Kurtosis:                      11.688   Cond. No.                     1.37e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.37e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [34]:
# 3、除了fisrev外，还控制fisrev和treat、year的交互项
df_long["year_fisrev"] = df_long["year"]*df_long["fisrev"]
df_long["treat_fisrev"] = df_long["treat"]*df_long["fisrev"]
did_3 = smf.ols("exp~treat+year+year_treat+fisrev+year_fisrev+treat_fisrev",data=df_long)
did_3 = did_3.fit()
print(did_3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    exp   R-squared:                       0.195
Model:                            OLS   Adj. R-squared:                  0.193
Method:                 Least Squares   F-statistic:                     85.59
Date:                Sun, 14 Jun 2026   Prob (F-statistic):           3.14e-96
Time:                        16:11:31   Log-Likelihood:                -16809.
No. Observations:                2124   AIC:                         3.363e+04
Df Residuals:                    2117   BIC:                         3.367e+04
Df Model:                           6
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      769.7098     71.349     10.788      0.000     629.788     909.632
treat          169.4106    119.915      1.413      0.158     -65.752     404.574
year           487.7305     45.859     10.635      0.000     397.797     577.664
year_treat     142.7878     73.336      1.947      0.052      -1.031     286.607
fisrev          -0.0145      0.005     -2.890      0.004      -0.024      -0.005
year_fisrev      0.0051      0.003      1.665      0.096      -0.001       0.011
treat_fisrev     0.0005      0.004      0.134      0.894      -0.007       0.008
==============================================================================
Omnibus:                      943.915   Durbin-Watson:                   0.975
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7867.046
Skew:                           1.893   Prob(JB):                         0.00
Kurtosis:                      11.635   Cond. No.                     2.69e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.69e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [37]:
''' 固定效应估计模式的实现，使用宽面板df '''
# 1、不控制人均财政收入
df["d_exp"] = df["exp2"]-df["exp1"]
df["d_fisrev"] = df["fisrev2"]-df["fisrev1"]
did_4 = smf.ols("d_exp~treat",data=df)
did_4 = did_4.fit()
print(did_4.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  d_exp   R-squared:                       0.014
Model:                            OLS   Adj. R-squared:                  0.013
Method:                 Least Squares   F-statistic:                     15.04
Date:                Sun, 14 Jun 2026   Prob (F-statistic):           0.000112
Time:                        16:21:12   Log-Likelihood:                -8085.3
No. Observations:                1062   AIC:                         1.617e+04
Df Residuals:                    1060   BIC:                         1.618e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    528.0045     16.733     31.554      0.000     495.170     560.839
treat        148.4418     38.273      3.878      0.000      73.342     223.542
==============================================================================
Omnibus:                      891.565   Durbin-Watson:                   1.946
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           130835.156
Skew:                          -3.113   Prob(JB):                         0.00
Kurtosis:                      57.018   Cond. No.                         2.65
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [38]:
# 2. 控制人均财政收入，取变化值df["d_fisrev"]
did_5 = smf.ols("d_exp~treat+d_fisrev",data=df)
did_5 = did_5.fit()
print(did_5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  d_exp   R-squared:                       0.014
Model:                            OLS   Adj. R-squared:                  0.012
Method:                 Least Squares   F-statistic:                     7.533
Date:                Sun, 14 Jun 2026   Prob (F-statistic):           0.000564
Time:                        16:22:37   Log-Likelihood:                -8085.3
No. Observations:                1062   AIC:                         1.618e+04
Df Residuals:                    1059   BIC:                         1.619e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    527.4811     16.960     31.102      0.000     494.203     560.759
treat        148.7191     38.318      3.881      0.000      73.532     223.906
d_fisrev       0.0002      0.001      0.193      0.847      -0.002       0.003
==============================================================================
Omnibus:                      892.211   Durbin-Watson:                   1.947
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           131276.024
Skew:                          -3.116   Prob(JB):                         0.00
Kurtosis:                      57.110   Cond. No.                     3.10e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.1e+04. This might indicate that there are
strong multicollinearity or other numerical problems.